pl: stub
	g++ -g -Wall -Iinc -I/usr/include/ ../../ut-fw/src/main_ut.cpp src/plUT.cpp -lcppunit -o bin/utPL

stub:
	g++ -g -Wall -fPIC -I/usr/include/ src/liboit_stubs.cpp -shared -o lib/liboit_stubs.so
