all:
	g++ -Wall  -g -I/home/eranbh/work/SHARKS/mem_db/common/inc -I/home/eranbh/work/SHARKS/threading/inc  -Iinc  -I/home/eranbh/work/SHARKS/mem_db/server/layouts/inc src/flow_manager.cpp -L/home/eranbh/work/SHARKS/mem_db/common -L/home/eranbh/work/SHARKS/threading -lmc_task  -lnet_intf -shared -o libflows.so 
