all:
	g++ -g -Wall -fPIC -shared -I../officer-common/inc -Iinc  -L/home/eran/work/lab/phone-officer/officer-common/lib  \
          src/agent_interception_points.c  -o lib/libagent.so -lpreloadutils -ldl
