all:
	g++  -g -Wall -std=c++1z  -Iframework  -Iclient -Itest main.cpp framework/src/StdStreamIODevice.cpp client/src/ClientUiTask.cpp client/src/UserManager.cpp  test/src/ClientUITest.cpp -o bin/msg-store -lpthread
