all:
	g++ -Wall  -g -I/home/eranbh/work/SHARKS/mem_db/common/inc -I/home/eranbh/work/SHARKS/threading/inc -I/home/eranbh/work/SHARKS/mem_db/server/layouts/inc  -Iflow/inc main.cpp -L/home/eranbh/work/SHARKS/mem_db/common -L/home/eranbh/work/SHARKS/threading -L/home/eranbh/work/SHARKS/mem_db/common -L/home/eranbh/work/SHARKS/mem_db/server/flow -lflows -lmc_task  -lnet_intf -lshm_intf  -o MEM_DB 
